[project]
name = "crypto-trading-strategies"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "freqtrade==2025.8",
    "pandas==2.3.2",
    "ta-lib==0.6.7",
    "yfinance>=0.2.66",
]
